/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views;

import javax.swing.JCheckBox;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;

public class DrawingMain extends javax.swing.JFrame {

    private DrawingPanel drawingPanel;

    public DrawingMain() {
        initComponents();
        setTitle("Simple Drawer");
        drawingPanel = (DrawingPanel) panDrawingArea;
        checkBoxRectangle.setSelected(false);
        checkBoxOval.setSelected(false);
        checkBoxTriangle.setSelected(false);
        checkBoxTriangle.setSelected(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDrawingArea = new DrawingPanel();
        menuBar = new javax.swing.JMenuBar();
        menuItemFile = new javax.swing.JMenu();
        menuItemImport = new javax.swing.JMenuItem();
        menuItemExport = new javax.swing.JMenuItem();
        menuItemEdit = new javax.swing.JMenu();
        menuItemReset = new javax.swing.JMenuItem();
        menuItemShapes = new javax.swing.JMenu();
        checkBoxRectangle = new javax.swing.JCheckBoxMenuItem();
        checkBoxOval = new javax.swing.JCheckBoxMenuItem();
        checkBoxTriangle = new javax.swing.JCheckBoxMenuItem();
        menuItemRotate = new javax.swing.JMenu();
        menuItemLeft = new javax.swing.JMenuItem();
        menuItemRight = new javax.swing.JMenuItem();
        menuItemColorMixer = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panDrawingArea.setBackground(new java.awt.Color(255, 255, 255));
        panDrawingArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panDrawingArea.setFocusCycleRoot(true);
        panDrawingArea.setPreferredSize(new java.awt.Dimension(800, 500));
        panDrawingArea.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panDrawingArea, "card2");

        menuItemFile.setText("     File     ");

        menuItemImport.setText("Import");

        menuItemFile.add(menuItemImport);

        menuItemExport.setText("Export");

        menuItemFile.add(menuItemExport);

        menuBar.add(menuItemFile);

        menuItemEdit.setText("     Edit     ");

        menuItemReset.setText("Reset");

        menuItemEdit.add(menuItemReset);

        menuBar.add(menuItemEdit);

        menuItemShapes.setText("     Shapes Dropdown     ");

        checkBoxRectangle.setText("Rectangle");

        menuItemShapes.add(checkBoxRectangle);

        checkBoxOval.setText("Oval");

        menuItemShapes.add(checkBoxOval);

        checkBoxTriangle.setText("Triangle");

        menuItemShapes.add(checkBoxTriangle);

        checkBoxLine.setText("Line");

        menuItemShapes.add(checkBoxLine);

        menuBar.add(menuItemShapes);

        menuItemRotate.setText("     Rotate     ");

        menuItemLeft.setText("Left");

        menuItemRotate.add(menuItemLeft);

        menuItemRight.setText("Right");

        menuItemRotate.add(menuItemRight);

        menuBar.add(menuItemRotate);

        menuItemColorMixer.setText("     Colour Mixer     ");

        menuBar.add(menuItemColorMixer);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JCheckBoxMenuItem getCheckBoxRectangle() {
        return checkBoxRectangle;
    }

    public JCheckBoxMenuItem getCheckBoxTriangle() {
        return checkBoxTriangle;
    }

    public JCheckBoxMenuItem getCheckBoxOval() {
        return checkBoxOval;
    }

    public JCheckBoxMenuItem getCheckBoxLine() {
        return checkBoxLine;
    }

    public JMenu getMenuItemFile() {
        return this.menuItemFile;
    }

    public JMenu getMenuItemEdit() {
        return this.menuItemEdit;
    }

    public JMenu getMenuItemColorMixer() {
        return this.menuItemColorMixer;
    }

    public JMenu getMenuItemShapes() {
        return this.menuItemShapes;
    }

    public JMenu getMenuItemRotate() {
        return this.menuItemRotate;
    }

    @Override
    public JMenuBar getMenuBar(){
        return this.menuBar;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem checkBoxRectangle;
    private javax.swing.JCheckBoxMenuItem checkBoxOval;
    private javax.swing.JCheckBoxMenuItem checkBoxTriangle;
    private JCheckBoxMenuItem checkBoxLine;
    private javax.swing.JMenu menuItemFile;
    private javax.swing.JMenu menuItemEdit;
    private javax.swing.JMenu menuItemColorMixer;
    private javax.swing.JMenu menuItemShapes;
    private javax.swing.JMenu menuItemRotate;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemExport;
    private javax.swing.JMenuItem menuItemImport;
    private javax.swing.JMenuItem menuItemReset;
    private javax.swing.JMenuItem menuItemLeft;
    private javax.swing.JMenuItem menuItemRight;
    public javax.swing.JPanel panDrawingArea;
    // End of variables declaration//GEN-END:variables
}
